version: '3.8'

services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - db:/data/db
            
    app:
        container_name: api
        depends_on:
            - mongodb
        user: 'node'
        restart: unless-stopped
        env_file: .env
        command: sh -c "yarn build && yarn start"
        ports:
            - ${PORT}:${PORT}
        environment:
            - TOKEN=${TOKEN}
            - PORT=${PORT}
            - MONGODB_ENABLED=${MONGODB_ENABLED}
            - MONGODB_URI=mongodb://mongodb:27017
        volumes:
            - ./:/home/node/app
        working_dir: /home/node/app
        image: node:18-alpine3.15
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    db:
